all:
	make -C ./simple_examples/blinky
	make -C ./at_demo
	make -C ./iot_demo
	make -C ./simple_examples/rtos_example
	make -C ./uart_example
	make -C ./simple_examples/gpiointerrupt_tcpsend
	make -C ./simple_examples/uart_send

clean:
	make -C ./simple_examples/blinky clean
	make -C ./at_demo clean
	make -C ./iot_demo clean
	make -C ./simple_examples/rtos_example clean
	make -C ./simple_examples/uart_send clean
	make -C ./uart_example clean
	make -C ./simple_examples/gpiointerrupt_tcpsend clean
